/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulation;

import OSPABA.SimState;
import OSPABA.Simulation;
import Objekty.Konstanty;
import Objekty.Vozidlo;
import agents.AgentNakladaca;
import agents.AgentStavby;
import agents.AgentVozidiel;
import agents.AgentVykladaca;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JSlider;

/**
 *
 * @author liesko3
 */
public class Gui2 extends javax.swing.JFrame implements OSPABA.ISimDelegate {

    /**
     * Creates new form Gui2
     */
    MySimulation ms = new MySimulation();
    private LinkedList<Vozidlo> listVGui = new LinkedList<>();

    public Gui2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jStatStavba = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jStatSkladka = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jStatHlavna = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelNakladac2 = new javax.swing.JLabel();
        jLabel1Nakladac1 = new javax.swing.JLabel();
        jLabelVykladac2 = new javax.swing.JLabel();
        jLabelVykladac1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextFPocetReplikaci = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider2 = new javax.swing.JSlider();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jBPause = new javax.swing.JButton();
        jBContinue = new javax.swing.JButton();
        jBspeed = new javax.swing.JButton();
        jBStart = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25CasHore = new javax.swing.JLabel();
        jBspeed1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jStatStavba.setColumns(20);
        jStatStavba.setRows(5);
        jStatStavba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane3.setViewportView(jStatStavba);

        jStatSkladka.setColumns(20);
        jStatSkladka.setRows(5);
        jStatSkladka.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane4.setViewportView(jStatSkladka);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Vykladac");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nakladac2");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Vykladac2");

        jStatHlavna.setColumns(20);
        jStatHlavna.setRows(5);
        jStatHlavna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane13.setViewportView(jStatHlavna);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("vykladka mnozstvo");

        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("0");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("material na skladke");

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("0");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Nakladac");

        jLabelNakladac2.setText("no active");

        jLabel1Nakladac1.setText("no active");

        jLabelVykladac2.setText("no active");

        jLabelVykladac1.setText("no active");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Priebezne statistiky pri nakladacoch");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Priebezne statistiky pri vykladacoch");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1Nakladac1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jLabelNakladac2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabelVykladac1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelVykladac2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1Nakladac1)
                            .addComponent(jLabel23)
                            .addComponent(jLabel12)
                            .addComponent(jLabelVykladac1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabelNakladac2)
                            .addComponent(jLabel20)
                            .addComponent(jLabelVykladac2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel6)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Vypocty                          ", jPanel1);
        jTabbedPane1.addTab("Graf vyvoja mnozstva materialu na skladke                                 ", jScrollPane1);
        jTabbedPane1.addTab("Graf vyvoja mnozstva materialu na stavbe", jScrollPane16);

        jLabel3.setText("pocet Replikacii");

        jLabel5.setText("% odsadenie v grafe");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kompletne dodavky", "3 mesiace dodavatl A" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFPocetReplikaci.setText("100");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(10, 0, 100, 1));

        jSlider2.setMaximum(2000);
        jSlider2.setMinimum(1);
        jSlider2.setMinorTickSpacing(20);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(1000);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider1.setMaximum(500);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(250);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel7.setText("delay");

        jBPause.setText("pause");
        jBPause.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPauseActionPerformed(evt);
            }
        });

        jBContinue.setText("continue");
        jBContinue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinueActionPerformed(evt);
            }
        });

        jBspeed.setText("speed");
        jBspeed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBspeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBspeedActionPerformed(evt);
            }
        });

        jBStart.setText("start");
        jBStart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBStartActionPerformed(evt);
            }
        });

        jButton5.setText("stop");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("interval");

        jCheckBox1.setText("pridat druhy vykladac");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto A1", "Auto A2", "Auto A3", "Auto A4", "Auto A5" }));

        jButton1.setText("add");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 20, 1));

        jLabel4.setText("pocet kusov");

        jCheckBox2.setText("graf skladka");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });

        jCheckBox3.setText("graf stavba");
        jCheckBox3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox3StateChanged(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane5.setViewportView(jTextArea4);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("zoznam vozidiel");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 0));
        jLabel24.setText("cas format : yy-mm-dd-hh-mm-ss");

        jLabel25CasHore.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25CasHore.setText("0");

        jBspeed1.setText("refresh");
        jBspeed1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBspeed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBspeed1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25CasHore, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFPocetReplikaci, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBspeed1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBStart, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBPause, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel25CasHore, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBPause)
                                    .addComponent(jBStart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBContinue)
                                    .addComponent(jButton5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBspeed)
                                    .addComponent(jBspeed1))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSlider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox2)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton1)
                                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFPocetReplikaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        setsimspeed(jSlider1, jSlider2);
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        setsimspeed(jSlider1, jSlider2);
    }//GEN-LAST:event_jSlider2StateChanged

    private void jBContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinueActionPerformed
        ms.resumeSimulation();
    }//GEN-LAST:event_jBContinueActionPerformed

    private void jBStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBStartActionPerformed
         ms.stopSimulation();
        ms = new MySimulation();
        ms.setListVozidiel(listVGui);
        ms.nulujAuta();
        jTable1.setModel(new TabModel(ms.getListVozidiel()));
        jStatHlavna.setText("  ");
        // ms.setSimSpeed(0.8, 0.01d);
        if (ms.getListVozidiel().size() == 0) {
            jTextArea4.setText("nie je vybrane ziadne vozidlo");
        } else {
            setsimspeed(jSlider1, jSlider2);
            if (jComboBox1.getSelectedIndex() == 0) {
                ms.setIsOdstaveny(false);
            } else {
                ms.setIsOdstaveny(true);
            }

            ms.registerDelegate(this);
            if (jCheckBox2.isSelected()) {
                ms.setIsGrafN(true);
                jScrollPane1.getViewport().add(ms.vratGraphN().getChartPanel());
            } else {
                ms.setIsGrafN(false);
            }
            if (jCheckBox3.isSelected()) {
                ms.setIsGrafV(true);
                jScrollPane16.getViewport().add(ms.vratGraphV().getChartPanel());
            } else {
                ms.setIsGrafV(false);
            }
            if (jCheckBox1.isSelected()) {
                ms.setIsDruhy(true);
                jTextArea4.setText(ms.vypisFront(ms.getListVozidiel()));
            } else {
                ms.setIsDruhy(false);
                jTextArea4.setText(ms.vypisFront(ms.getListVozidiel()));
            }
            ms.setFinishArea(jStatHlavna);
            ms.setOdsadenie(Integer.parseInt(jSpinner1.getValue().toString()));
            jBStart.setFocusable(false);

            ms.simulate(Integer.parseInt(jTextFPocetReplikaci.getText().trim()));

        }
    }//GEN-LAST:event_jBStartActionPerformed

    private void jBPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPauseActionPerformed
//jStavSimulacie.setText("pozastavena");
        ms.pauseSimulation();
//jStavSimulacie.setText("pozastavena");

    }//GEN-LAST:event_jBPauseActionPerformed

    private void jBspeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBspeedActionPerformed
      jStatHlavna.setText("prebieha rychly rezim");
      jStatSkladka.setText("");
      jStatStavba.setText("");
        ms.setMaxSimSpeed();

    }//GEN-LAST:event_jBspeedActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     //   jStavSimulacie.setText("pozastavena");
        ms.stopSimulation();
        ms = new MySimulation();
        ms.setListVozidiel(listVGui);
        ms.nulujAuta();
        jTextArea4.setText(ms.vypisFront(ms.getListVozidiel()));
        jStatHlavna.setText("");
        jStatSkladka.setText("");
        jStatStavba.setText("");


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ms.addCar(jComboBox2.getSelectedIndex(), Integer.parseInt(jSpinner2.getValue().toString()));
        //listVGui.add(jComboBox2.getSelectedIndex(), Integer.parseInt(jSpinner2.getValue().toString()));
        addCar(jComboBox2.getSelectedIndex(), Integer.parseInt(jSpinner2.getValue().toString()));
        ms.setListVozidiel(listVGui);
        jTextArea4.setText(ms.vypisFront(ms.getListVozidiel()));
        jTable1.setModel(new TabModel(ms.getListVozidiel()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if (jCheckBox1.isSelected()) {
            ms.setIsDruhy(true);

        } else {
            ms.setIsDruhy(false);
        }
        jTextArea4.setText(ms.vypisFront(ms.getListVozidiel()));
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        if (jCheckBox2.isSelected()) {
            ms.setIsGrafN(true);
            jScrollPane1.getViewport().add(ms.vratGraphN().getChartPanel());
        } else {
            ms.setIsGrafN(false);
        }
    }//GEN-LAST:event_jCheckBox2StateChanged

    private void jCheckBox3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox3StateChanged
        if (jCheckBox3.isSelected()) {
            ms.setIsGrafV(true);
            jScrollPane16.getViewport().add(ms.vratGraphV().getChartPanel());
        } else {
            ms.setIsGrafV(false);
        }
    }//GEN-LAST:event_jCheckBox3StateChanged

    private void jBspeed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBspeed1ActionPerformed
        listVGui = new LinkedList<>();
        ms.setListVozidiel(listVGui);
        jTextArea4.setText("");
        jTable1.setModel(new TabModel(ms.getListVozidiel()));
    }//GEN-LAST:event_jBspeed1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBContinue;
    private javax.swing.JButton jBPause;
    private javax.swing.JButton jBStart;
    private javax.swing.JButton jBspeed;
    private javax.swing.JButton jBspeed1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1Nakladac1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25CasHore;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNakladac2;
    private javax.swing.JLabel jLabelVykladac1;
    private javax.swing.JLabel jLabelVykladac2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jStatHlavna;
    private javax.swing.JTextArea jStatSkladka;
    private javax.swing.JTextArea jStatStavba;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextFPocetReplikaci;
    // End of variables declaration//GEN-END:variables

    @Override
    public void simStateChanged(Simulation smltn, SimState ss) {
        //ms = new MySimulation();
    }

    @Override
    public void refresh(Simulation smltn) {
       
        String s2 = (dateZapis(new Date((long) (smltn.currentTime() * Math.pow(10, 3)))));
        ((TabModel) jTable1.getModel()).fireTableDataChanged();
    //    if (ms.isPaused() == true) {
//            jStavSimulacie.setText("pozastavena");
       // }else{ jStavSimulacie.setText("prebieha");}

        if (ms.isRunning() == false) {
            jStatSkladka.setText("");
            jStatStavba.setText("");
        } else {
            jStatHlavna.setText(ms.vypisVsetko());
            jStatSkladka.setText(ms.vypisSkladku());
            jStatStavba.setText(ms.vypisStavbu());
        }
//        jLabel22.setText(s2);
        jLabel25CasHore.setText(s2);
//        areaNakladacFront.setText(((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).vypisFront(((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getListVozidielNakladac()));
        //     areaVykladacFront.setText(((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).vypisFront(((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getListVozidielVykladac()));
        // prepocet auta

        Vozidlo vozn = ((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getVozVNakladaci();
        if (vozn == null) {
            jLabel1Nakladac1.setText("no active");
        } else if (vozn.getTyp() != null) {
            vozn.prepocitaHodnotu(ms.currentTime(), Konstanty.vykonNakladac);
            jLabel1Nakladac1.setText(vozn.toString());
        } else {
            jLabel1Nakladac1.setText("no active");
        }
        Vozidlo vozn2 = ((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getVozVNakladaci2();
        if (vozn2 == null) {
            jLabelNakladac2.setText("no active");
        } else if (vozn2.getTyp() != null) {
            vozn2.prepocitaHodnotu(ms.currentTime(), Konstanty.vykonNakladac2);
            jLabelNakladac2.setText(vozn2.toString());
        } else {
            jLabelNakladac2.setText("no active");
        }

        if (vozn != null && vozn2 != null) {
            jLabel6.setText(((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getNalozene() - vozn.getObjemnaVykreslenie()
                    - vozn2.getObjemnaVykreslenie() + ""
            );
        } else if (vozn != null && vozn2 == null) {
            jLabel6.setText(((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getNalozene()
                    - vozn.getObjemnaVykreslenie() + ""
            );
        } else if (vozn == null && vozn2 != null) {
            jLabel6.setText(((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getNalozene() - vozn2.getObjemnaVykreslenie()
                    + ""
            );
        } else {
            jLabel6.setText(((AgentNakladaca) smltn.findAgent(Id.agentNakladaca)).getNalozene() + ""
            );
        }

        Vozidlo vozv = ((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getVozVykladaci();
        if (vozv == null) {
            jLabelVykladac1.setText("no active");
        } else if (vozv.getTyp() != null) {
            vozv.prepocitaOdpocetHodnotu(ms.currentTime(), Konstanty.vykonVykladac);
            jLabelVykladac1.setText(vozv.toString());
        } else {
            jLabelVykladac1.setText("no active");
        }
        Vozidlo vozv2 = ((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getVozVykladaci2();
        if (vozv2 == null) {
            jLabelVykladac2.setText("no active");
        } else if (vozv2.getTyp() != null) {
            vozv2.prepocitaOdpocetHodnotu(ms.currentTime(), Konstanty.vykonVykladac);
            jLabelVykladac2.setText(vozv2.toString());
        } else {
            jLabelVykladac2.setText("no active");
        }

        if (vozv != null && vozv2 != null) {
            jLabel21.setText(((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getVylozeneMnozstvo() + vozv.getObjemnaVykreslenie()
                    + vozv2.getObjemnaVykreslenie() + ""
            );
        } else if (vozv != null && vozv2 == null) {
            jLabel21.setText(((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getVylozeneMnozstvo()
                    + vozv.getObjemnaVykreslenie() + ""
            );
        } else if (vozv == null && vozv2 != null) {
            jLabel21.setText(((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getVylozeneMnozstvo() + vozv2.getObjemnaVykreslenie()
                    + ""
            );
        } else {
            jLabel21.setText(((AgentVykladaca) smltn.findAgent(Id.agentVykladaca)).getVylozeneMnozstvo() + ""
            );
        }

        //    areaAB.setText(((AgentVozidiel) smltn.findAgent(Id.agentVozidiel)).vypisFront(((AgentVozidiel) smltn.findAgent(Id.agentVozidiel)).getFrontCestaAB()));
        //      areaBC.setText(((AgentVozidiel) smltn.findAgent(Id.agentVozidiel)).vypisFront(((AgentVozidiel) smltn.findAgent(Id.agentVozidiel)).getFrontCestaBC()));
        //      areaCA.setText(((AgentVozidiel) smltn.findAgent(Id.agentVozidiel)).vypisFront(((AgentVozidiel) smltn.findAgent(Id.agentVozidiel)).getFrontCestaCA()));
    }

    public void setsimspeed(JSlider delays, JSlider intervals) {
        double delay = (double) delays.getValue() / 100;
        double interval = (double) intervals.getValue() / 100;
        ms.setSimSpeed(interval, delay);
    }

    public static String dateZapis(Date date) {
        return (date.getYear() - 70) + "-" + (date.getMonth()) + "-" + (date.getDate() - 1) + "-" + (date.getHours() - 1) + "-" + date.getMinutes() + "-" + date.getSeconds();
    }

    public LinkedList<Vozidlo> getListVGui() {
        return listVGui;
    }

    public void setListVGui(LinkedList<Vozidlo> listVGui) {
        this.listVGui = listVGui;
    }

    public void addCar(int i, int j) {
        if (i == 0) {
            for (int k = 0; k < j; k++) {
                listVGui.add(new Vozidlo("A1"));
            }

        }
        if (i == 1) {
            for (int k = 0; k < j; k++) {
                listVGui.add(new Vozidlo("A2"));
            }
        }
        if (i == 2) {
            for (int k = 0; k < j; k++) {
                listVGui.add(new Vozidlo("A3"));
            }
        }
        if (i == 3) {
            for (int k = 0; k < j; k++) {
                listVGui.add(new Vozidlo("A4"));
            }
        }
        if (i == 4) {
            for (int k = 0; k < j; k++) {
                listVGui.add(new Vozidlo("A5"));
            }
        }

    }
       public void nulujAuta() {
        for (Vozidlo voz : listVGui) {
            voz.nuluj();
        }
    }
}
